package com.example.droidly

import com.example.droidly.ui.navigation.Screen
import androidx.navigation.NavController
import androidx.compose.runtime.Composable
import com.example.droidly.ui.view.*
import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

/**
* GENERATED BY DROIDLY BLOCK BUILDER
**/


object Home : Screen("Home", { Home(it) }, false, null)
object SecondScreen : Screen("SecondScreen", { SecondScreen(it) }, false, null)

object Screens {
    val startScreenRoute: String = Home.route
    val allScreens = listOf(
        Home,
        SecondScreen,
    )
}

@Composable
fun Home(navController: NavController) {
    Column(
        modifier = Modifier
            .padding(all = 10.dp),
    ) {
        DroidlyText(
            modifier = Modifier,
            text = "Home",
            fontSize = 24.sp,
            fontWeight = FontWeight.W700,
        )
        DroidlySurface(
            modifier = Modifier,
            elevation = 6.dp,
            shape = RoundedCornerShape(percent = 20),
            border = BorderStroke(2.dp, Color(0xFF5f27cd)),
            onClick = { navController.navigate("SecondScreen") }
        ) {
            DroidlyText(
                modifier = Modifier,
                text = "Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum ",
            )
        }
    }
}

@Composable
fun SecondScreen(navController: NavController) {
    Box(
        modifier = Modifier
            .padding(all = 12.dp),
    ) {
        DroidlyText(
            modifier = Modifier,
            text = "Some text Some text Some text ",
        )
    }
}
